---
language: python
services: docker

env:
  global:
    - ROLE_NAME: scratch_mqtt
  matrix:
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint flake8 docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-scratch-mqtt bassinator.$ROLE_NAME
  - cd bassinator.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
